package com.br.finnet.integracaoAdiq.domain.enums;

public enum CurrencyEnum {
    ADA("ADA"),
    AE("AE"),
    ATOM("ATOM"),
    AUD("AUD"),
    BAT("BAT"),
    BCD("BCD"),
    BC("BCH"),
    BCN("BCN"),
    BNB("BNB"),
    BRL("BRL"),
    BSV("BSV"),
    BTC("BTC"),
    BTG("BTG"),
    BTM("BTM"),
    BTS("BTS"),
    CAD("CAD"),
    CHF("CHF"),
    CNY("CNY"),
    CZK("CZK"),
    DAI("DAI"),
    DASH("DASH"),
    DCR("DCR"),
    DGB("DGB"),
    DKK("DKK"),
    DOGE("DOGE"),
    EOS("EOS"),
    ETC("ETC"),
    ETH("ETH"),
    EUR("EUR"),
    GBP("GBP"),
    GNO("GNO"),
    GNT("GNT"),
    HKD("HKD"),
    HUF("HUF"),
    HUS("HUSD"),
    ICX("ICX"),
    ILS("ILS"),
    INR("INR"),
    IOTA("IOTA"),
    JPY("JPY"),
    KCS("KCS"),
    KFEE("KFEE"),
    KRW("KRW"),
    LINK("LINK"),
    LSK("LSK"),
    LTC("LTC"),
    MKR("MKR"),
    MLN("MLN"),
    MONA("MONA"),
    MXN("MXN"),
    MYR("MYR"),
    NANO("NANO"),
    NEO("NEO"),
    NOK("NOK"),
    NPXS("NPXS"),
    NZD("NZD"),
    OMG("OMG"),
    ONT("ONT"),
    PAXG("PAXG"),
    PLN("PLN"),
    QTUM("QTUM"),
    REP("REP"),
    RUB("RUB"),
    SC("SC"),
    SEK("SEK"),
    SGD("SGD"),
    STEEM("STEEM"),
    STRAT("STRAT"),
    THB("THB"),
    TRX("TRX"),
    TRY("TRY"),
    TWD("TWD"),
    USD("USD"),
    USDC("USDC"),
    USDT("USDT"),
    VEN("VEN"),
    WAN("WAN"),
    WAVES("WAVES"),
    WTC("WTC"),
    XBT("XBT"),
    XDG("XDG"),
    XEM("XEM"),
    XLM("XLM"),
    XMR("XMR"),
    XRP("XRP"),
    XTZ("XTZ"),
    XVG("XVG"),
    ZAR("ZAR"),
    ZEC("ZEC"),
    ZIL("ZIL"),
    ZRX("ZRX");

    public String codCurrency;

    CurrencyEnum(String codCurrency) {
        this.codCurrency = codCurrency;
    }

    public String getCodCurrency() {
        return codCurrency;
    }

}
